### ISSUE TITLE
Interface is broken for version 2.5.0

### ISSUE THREAD

**Issue by CristianCantoro** [pataquets/docker-boinctui#1]
Here's a screenshot of the latest build of docker-boinctui (`v2.5.0.`)
![Screenshot of docker-boinctui w/ broken interfaced](https://i.imgur.com/jxzr5Hq.png)

It can be fixed setting the `TERM` env variable to `screen`:

```
docker run \
  -it \
  --rm \
  --name=boinctui \
  --net=host \
  -e TERM='screen' \
  pataquets/boinctui
```
![Screenshot of docker-boinctui w/ broken interfaced](https://i.imgur.com/D5ssoZM.png)

**Comment by pataquets** [comment]
When running TUI progrms using Docker, I always add `-e TERM` switch, along some other vars such as `TZ`, `LANG` and `LC_ALL` (actually I have an alias defined) to avoid issues like this. Notice that they are passed without explicitly setting any value, so they are set to the current environment's values. 

I've given some love to the image lately. Mainly, upgraded from Focal to Jammy (boinctui 2.5.0 -> 2.6.0) and added a build and push image to Docker Hub Github Action.

Let me know if you still have problems.
